CREATE TABLE IF NOT EXISTS warehousing_requests (
  id int(11) NOT NULL AUTO_INCREMENT,
  request_ref varchar(50) NOT NULL,
  request_type enum('replenishment','spare_parts','stock_transfer','issuance','asset_item') NOT NULL DEFAULT 'replenishment',
  item_id int(11) DEFAULT NULL,
  item_name varchar(150) NOT NULL,
  quantity int(11) NOT NULL,
  status enum('Pending','Processing','Fulfilled','Rejected') NOT NULL DEFAULT 'Pending',
  priority enum('Low','Normal','High','Urgent') NOT NULL DEFAULT 'Normal',
  requested_by int(11) DEFAULT NULL,
  source_module varchar(80) NOT NULL,
  source_system varchar(80) DEFAULT NULL,
  source_reference varchar(120) NOT NULL,
  notes varchar(255) DEFAULT NULL,
  source_payload longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(source_payload)),
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (id),
  KEY idx_wh_req_ref (request_ref),
  KEY idx_wh_req_type (request_type),
  KEY idx_wh_req_status (status),
  KEY idx_wh_req_source (source_module,source_reference),
  KEY fk_wh_req_item (item_id),
  KEY fk_wh_req_requested_by (requested_by),
  CONSTRAINT fk_wh_req_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE SET NULL,
  CONSTRAINT fk_wh_req_requested_by FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
