CREATE TABLE IF NOT EXISTS asset_requests (
  id int(11) NOT NULL AUTO_INCREMENT,
  request_ref varchar(50) NOT NULL,
  request_type enum('registration','allocation','status_update') NOT NULL DEFAULT 'registration',
  asset_tag varchar(60) DEFAULT NULL,
  asset_name varchar(150) NOT NULL,
  asset_category varchar(100) DEFAULT NULL,
  quantity int(11) NOT NULL DEFAULT 1,
  status enum('Pending','Processing','Fulfilled','Rejected') NOT NULL DEFAULT 'Pending',
  priority enum('Low','Normal','High','Urgent') NOT NULL DEFAULT 'Normal',
  requested_by int(11) DEFAULT NULL,
  source_module varchar(80) NOT NULL,
  source_system varchar(80) DEFAULT NULL,
  source_reference varchar(120) NOT NULL,
  notes varchar(255) DEFAULT NULL,
  source_payload longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(source_payload)),
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (id),
  KEY idx_asset_req_ref (request_ref),
  KEY idx_asset_req_type (request_type),
  KEY idx_asset_req_status (status),
  KEY idx_asset_req_source (source_module,source_reference),
  KEY fk_asset_req_requested_by (requested_by),
  CONSTRAINT fk_asset_req_requested_by FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
